---
title: "Reading monthy US tornado data"
author: "Craig W. Slinkman"
date: "6/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Instruction  

This document is used to development of the Inited States tonado data.

## Preperation

```{r}
library( tidyverse )
library( stringr )
library( lubridate )
library( tidyr )
library( purrr )
```

## Load functions

```{r}
 source('D:/R-Projects/Tornadoes/functions/get_file_names.R')
 source('D:/R-Projects/Tornadoes/functions/get_file.R')
```

## Get list of monthly data files

```{r}

d_path  <- file.path( getwd(),     # Specify the director path to the data
                      "data",      # files ... 
                      "months")

files <- dir( d_path )              # Get the all the file names ...

tornadoes  <-                                  # Build combines tornado file by ...
  file.path( d_path, files ) %>%    # Use file paths to ...
    map( get_file ) %>%             # To read each monthly files ... 
    reduce( bind_rows )

                          
 
                                     .
```



```{r}
data <- files %>%
  map(read_csv) %>%    # read in all the files individually, using
                       # the function read_csv() from the readr package
    reduce(bind_rows)  # reduce bind_rows into one tibble
data
```


## Bind all the tibbles in the months list into a single tibble

```{r}
tornadoes <- bind_rows( months )
tornadoes
```
## Change column names to lowercase to be compatible with tidyverse naming conventions

```{r}
names( tornadoes) <- tolower( names( tornadoes ))
tornadoes
```
## Create date-time POSIX object add add to tornaoes tibble

```{r}
names(tornadoes)

temp_date <-     pull( begin_date )
temp_date

temp_time <- 
  tornadoes %>% 
    pull()
```